# Generated by Django 5.0.6 on 2024-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_uploadimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='Image',
        ),
    ]
