# Generated by Django 5.0.6 on 2024-05-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_uploadimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='finger_image',
        ),
    ]
