# Generated by Django 5.0.6 on 2024-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_image_finger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finger_image',
            name='image',
            field=models.ImageField(upload_to='finger_images'),
        ),
    ]
