# Generated by Django 5.0.6 on 2024-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='QR_images')),
            ],
        ),
    ]
