# Generated by Django 5.0.6 on 2024-06-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_qr_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_image',
            old_name='caption',
            new_name='bill_id',
        ),
    ]
