# Generated by Django 5.0.6 on 2024-06-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_caption_qr_image_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_image',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
